import { Case, Hearing, Notification, Role } from './types';

export const CASES: Case[] = [
  {
    id: 'NS-2025-001',
    title: 'State vs. Malhotra',
    type: 'Criminal',
    court: 'Supreme Court of India',
    date: '2024-11-12',
    status: 'Hearing',
    next: '2025-04-15',
    judge: 'Hon. Justice D.Y. Chandrachud',
    lawyer: 'Adv. Harish Salve',
    lawyerBio: 'Senior Advocate with 40+ years experience in constitutional law.',
    lawyerWins: 450,
    lawyerTotal: 520,
    lawyerYears: 42,
    defLawyer: 'Adv. Kapil Sibal',
    defLawyerBio: 'Renowned criminal lawyer and former Union Minister.',
    defLawyerWins: 410,
    defLawyerTotal: 490,
    defLawyerYears: 38,
    defendant: 'Vikram Malhotra',
    keyArguments: ['Lack of direct evidence', 'Procedural lapses in investigation', 'Alibi verification'],
    complexity: 'Very High'
  },
  {
    id: 'NS-2025-002',
    title: 'Reliance vs. Tata Group',
    type: 'Civil',
    court: 'Delhi High Court',
    date: '2024-12-05',
    status: 'Judgment Pending',
    next: '—',
    judge: 'Hon. Justice Manmohan',
    lawyer: 'Adv. Mukul Rohatgi',
    lawyerBio: 'Former Attorney General of India.',
    lawyerWins: 380,
    lawyerTotal: 430,
    lawyerYears: 35,
    defLawyer: 'Adv. Abhishek Singhvi',
    defLawyerBio: 'Specialist in corporate and commercial litigation.',
    defLawyerWins: 350,
    defLawyerTotal: 410,
    defLawyerYears: 32,
    defendant: 'Tata Sons Pvt Ltd',
    keyArguments: ['Contractual breach', 'Intellectual property infringement', 'Market dominance abuse'],
    complexity: 'High'
  },
  {
    id: 'NS-2025-003',
    title: 'Sharma Property Dispute',
    type: 'Family',
    court: 'District Court, Saket',
    date: '2025-01-20',
    status: 'Filed',
    next: '2025-05-10',
    judge: 'Hon. Judge R.K. Gupta',
    lawyer: 'Adv. Meenakshi Lekhi',
    lawyerBio: 'Expert in family and property law.',
    lawyerWins: 120,
    lawyerTotal: 150,
    lawyerYears: 20,
    defLawyer: 'Adv. Pinky Anand',
    defLawyerBio: 'Specialist in civil and family matters.',
    defLawyerWins: 110,
    defLawyerTotal: 145,
    defLawyerYears: 22,
    defendant: 'Anil Sharma',
    keyArguments: ['Ancestral property rights', 'Will validity', 'Partition claim'],
    complexity: 'Medium'
  },
  {
    id: 'NS-2025-004',
    title: 'Environmental Protection vs. Union',
    type: 'Constitutional',
    court: 'National Green Tribunal',
    date: '2024-10-15',
    status: 'Closed',
    next: '—',
    judge: 'Hon. Justice Prakash Shrivastava',
    lawyer: 'Adv. Prashant Bhushan',
    lawyerBio: 'Public interest litigation specialist.',
    lawyerWins: 200,
    lawyerTotal: 350,
    lawyerYears: 30,
    defLawyer: 'Adv. Tushar Mehta',
    defLawyerBio: 'Solicitor General of India.',
    defLawyerWins: 300,
    defLawyerTotal: 400,
    defLawyerYears: 28,
    defendant: 'Ministry of Environment',
    keyArguments: ['Ecological impact', 'Sustainable development', 'Regulatory compliance'],
    complexity: 'Very High'
  },
  {
    id: 'NS-2025-005',
    title: 'TechCorp vs. StartupX',
    type: 'Civil',
    court: 'Karnataka High Court',
    date: '2025-02-10',
    status: 'Hearing',
    next: '2025-04-22',
    judge: 'Hon. Justice N.V. Anjaria',
    lawyer: 'Adv. Gopal Subramanium',
    lawyerBio: 'Former Solicitor General with expertise in commercial law.',
    lawyerWins: 320,
    lawyerTotal: 380,
    lawyerYears: 34,
    defLawyer: 'Adv. Arvind Datar',
    defLawyerBio: 'Constitutional and tax law expert.',
    defLawyerWins: 290,
    defLawyerTotal: 340,
    defLawyerYears: 31,
    defendant: 'StartupX Solutions',
    keyArguments: ['Patent infringement', 'Trade secret theft', 'Non-compete clause'],
    complexity: 'High'
  },
  {
    id: 'NS-2025-006',
    title: 'Marine Logistics vs. Port Authority',
    type: 'Civil',
    court: 'Bombay High Court',
    date: '2025-01-15',
    status: 'Hearing',
    next: '2025-04-30',
    judge: 'Hon. Justice Devendra Kumar Upadhyaya',
    lawyer: 'Adv. Janak Dwarkadas',
    lawyerBio: 'Senior Advocate specializing in commercial and maritime law.',
    lawyerWins: 280,
    lawyerTotal: 320,
    lawyerYears: 30,
    defLawyer: 'Adv. Rafique Dada',
    defLawyerBio: 'Expert in constitutional and administrative law.',
    defLawyerWins: 260,
    defLawyerTotal: 310,
    defLawyerYears: 33,
    defendant: 'Mumbai Port Trust',
    keyArguments: ['Lease agreement violation', 'Arbitrary fee hike', 'Operational delays'],
    complexity: 'High'
  },
  {
    id: 'NS-2025-007',
    title: 'Textile Workers Union vs. Mills',
    type: 'Civil',
    court: 'Madras High Court',
    date: '2024-11-20',
    status: 'Filed',
    next: '2025-05-05',
    judge: 'Hon. Justice K.R. Shriram',
    lawyer: 'Adv. P.S. Raman',
    lawyerBio: 'Former Advocate General of Tamil Nadu.',
    lawyerWins: 190,
    lawyerTotal: 230,
    lawyerYears: 25,
    defLawyer: 'Adv. Vijay Narayan',
    defLawyerBio: 'Specialist in labor and service law.',
    defLawyerWins: 180,
    defLawyerTotal: 220,
    defLawyerYears: 27,
    defendant: 'Coimbatore Textile Mills',
    keyArguments: ['Minimum wage non-compliance', 'Unsafe working conditions', 'Illegal layoffs'],
    complexity: 'Medium'
  },
  {
    id: 'NS-2025-008',
    title: 'Heritage Trust vs. State',
    type: 'Constitutional',
    court: 'Calcutta High Court',
    date: '2025-02-01',
    status: 'Hearing',
    next: '2025-04-28',
    judge: 'Hon. Justice T.S. Sivagnanam',
    lawyer: 'Adv. Jayanta Mitra',
    lawyerBio: 'Senior Advocate with expertise in civil and constitutional matters.',
    lawyerWins: 240,
    lawyerTotal: 290,
    lawyerYears: 35,
    defLawyer: 'Adv. Kishore Datta',
    defLawyerBio: 'Advocate General for West Bengal.',
    defLawyerWins: 220,
    defLawyerTotal: 280,
    defLawyerYears: 30,
    defendant: 'West Bengal Heritage Commission',
    keyArguments: ['Preservation of historical sites', 'Illegal construction permits', 'Public trust doctrine'],
    complexity: 'High'
  },
  {
    id: 'NS-2025-009',
    title: 'Land Acquisition vs. NHAI',
    type: 'Civil',
    court: 'Allahabad High Court',
    date: '2024-12-10',
    status: 'Judgment Pending',
    next: '—',
    judge: 'Hon. Justice Arun Bhansali',
    lawyer: 'Adv. Shashi Nandan',
    lawyerBio: 'Expert in land acquisition and revenue law.',
    lawyerWins: 150,
    lawyerTotal: 180,
    lawyerYears: 28,
    defLawyer: 'Adv. Manish Goyal',
    defLawyerBio: 'Additional Advocate General for UP.',
    defLawyerWins: 140,
    defLawyerTotal: 175,
    defLawyerYears: 25,
    defendant: 'NHAI',
    keyArguments: ['Inadequate compensation', 'Lack of rehabilitation plan', 'Procedural errors in notification'],
    complexity: 'Medium'
  },
  {
    id: 'NS-2025-010',
    title: 'Diamond Export vs. Customs',
    type: 'Civil',
    court: 'Gujarat High Court',
    date: '2025-01-05',
    status: 'Hearing',
    next: '2025-05-12',
    judge: 'Hon. Justice Sunita Agarwal',
    lawyer: 'Adv. Mihir Thakore',
    lawyerBio: 'Senior Advocate specializing in tax and commercial law.',
    lawyerWins: 210,
    lawyerTotal: 250,
    lawyerYears: 32,
    defLawyer: 'Adv. Kamal Trivedi',
    defLawyerBio: 'Advocate General for Gujarat.',
    defLawyerWins: 200,
    defLawyerTotal: 245,
    defLawyerYears: 34,
    defendant: 'Department of Customs',
    keyArguments: ['Duty drawback claim', 'Incorrect classification of goods', 'Seizure of assets'],
    complexity: 'High'
  },
  {
    id: 'NS-2025-011',
    title: 'Mining Rights vs. Tribal Council',
    type: 'Constitutional',
    court: 'Rajasthan High Court',
    date: '2024-10-25',
    status: 'Closed',
    next: '—',
    judge: 'Hon. Justice Manindra Mohan Shrivastava',
    lawyer: 'Adv. M.S. Singhvi',
    lawyerBio: 'Former Advocate General of Rajasthan.',
    lawyerWins: 170,
    lawyerTotal: 210,
    lawyerYears: 29,
    defLawyer: 'Adv. R.N. Mathur',
    defLawyerBio: 'Specialist in constitutional and administrative law.',
    defLawyerWins: 160,
    defLawyerTotal: 205,
    defLawyerYears: 31,
    defendant: 'Rajasthan State Mines & Minerals Ltd',
    keyArguments: ['Violation of tribal land rights', 'Environmental degradation', 'Lack of community consent'],
    complexity: 'Very High'
  },
  {
    id: 'NS-2025-012',
    title: 'Fishermen Association vs. Coastal Dev',
    type: 'Civil',
    court: 'Kerala High Court',
    date: '2025-02-15',
    status: 'Filed',
    next: '2025-06-01',
    judge: 'Hon. Justice A.J. Desai',
    lawyer: 'Adv. P. Ravindran',
    lawyerBio: 'Expert in maritime and environmental law.',
    lawyerWins: 130,
    lawyerTotal: 160,
    lawyerYears: 24,
    defLawyer: 'Adv. K. Gopalakrishna Kurup',
    defLawyerBio: 'Advocate General for Kerala.',
    defLawyerWins: 125,
    defLawyerTotal: 155,
    defLawyerYears: 26,
    defendant: 'Kerala Coastal Zone Management Authority',
    keyArguments: ['Livelihood protection', 'CRZ notification violation', 'Impact on marine ecosystem'],
    complexity: 'Medium'
  }
];

export const HEARINGS: Hearing[] = [
  { date: '2025-04-15', caseId: 'NS-2025-001', court: 'Supreme Court', time: '10:30 AM', type: 'Final Arguments' },
  { date: '2025-04-22', caseId: 'NS-2025-005', court: 'Karnataka High Court', time: '11:00 AM', type: 'Evidence Submission' },
  { date: '2025-05-10', caseId: 'NS-2025-003', court: 'Saket District Court', time: '02:30 PM', type: 'Preliminary Hearing' },
  { date: '2025-04-18', caseId: 'NS-2025-001', court: 'Supreme Court', time: '10:30 AM', type: 'Cross Examination' }
];

export const NOTIFICATIONS: Record<Role, Notification[]> = {
  Client: [
    { id: '1', title: 'Hearing Scheduled', msg: 'Your hearing for NS-2025-001 is on April 15th.', time: '2h ago', type: 'info', read: false },
    { id: '2', title: 'Document Required', msg: 'Please upload your alibi verification documents.', time: '5h ago', type: 'warn', read: false }
  ],
  Lawyer: [
    { id: '3', title: 'New Case Assigned', msg: 'You have been assigned to NS-2025-005.', time: '1h ago', type: 'success', read: false },
    { id: '4', title: 'Deadline Approaching', msg: 'Submit evidence for TechCorp vs StartupX by tomorrow.', time: '3h ago', type: 'danger', read: false }
  ],
  Judge: [
    { id: '5', title: 'Judgment Due', msg: 'Judgment for NS-2025-002 is due in 3 days.', time: '1h ago', type: 'purple', read: false },
    { id: '6', title: 'Bench Meeting', msg: 'Meeting with the bench at 4:00 PM today.', time: '4h ago', type: 'info', read: false }
  ],
  Court: [
    { id: '7', title: 'Filing Queue', msg: '5 new cases pending registration.', time: '30m ago', type: 'warn', read: false },
    { id: '8', title: 'Registry Log', msg: 'Daily registry log updated successfully.', time: '6h ago', type: 'success', read: false }
  ],
  Builder: [
    { id: '9', title: 'System Update', msg: 'Platform-wide analytics engine updated.', time: '10m ago', type: 'info', read: false },
    { id: '10', title: 'Security Alert', msg: 'Unauthorized access attempt blocked.', time: '1h ago', type: 'danger', read: false }
  ]
};

export const ROLE_CONFIG = {
  Client: { subLabel: 'Petitioner · Respondent', access: 'Full case view — read-only' },
  Lawyer: { subLabel: 'Advocate · Legal Counsel', access: 'Templates, translator, AI tools' },
  Judge: { subLabel: 'Judicial Officer', access: 'Lawyer vs Defence analysis, case bench' },
  Court: { subLabel: 'Judicial Jurisdiction', access: 'Court-specific case management' },
  Builder: { subLabel: 'Admin / System Access', access: 'Platform-wide analytics' }
};

export const STATUS_COLORS = {
  'Hearing': { bg: '#744210', fg: '#ECC94B' },
  'Filed': { bg: '#1A365D', fg: '#63B3ED' },
  'Judgment Pending': { bg: '#322659', fg: '#B794F4' },
  'Closed': { bg: '#22543D', fg: '#48BB78' }
};
